# Generated by Django 4.2.1 on 2023-06-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
