# Generated by Django 4.2.1 on 2023-06-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_estatus_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
