# Generated by Django 4.2.1 on 2023-06-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_estatus_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus',
            name='estado',
            field=models.CharField(max_length=255),
        ),
    ]
