# Generated by Django 4.2.1 on 2023-06-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.IntegerField()),
            ],
        ),
    ]
